output:
  plugins:
    - name: elasticsearch
      type: default
      options: 
        host: elasticsearch.logging.svc.cluster.local
        port: 9200
        scheme: http
        logstash_format: true
        include_tag_key: true
        tag_key: "@log_name"
        flush_interval: 1s
